# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: jeevanrameshyjr@gmail.com
author_name: JEEVAN-RY
contract_name: executor
deployment_language: typescript
preset_name: starter
project_name: microflux-contracts

