import React, { useState, useCallback } from 'react';
import { api } from '../services/api';
import type { AIWorkflowResult, AINode, AIEdge } from '../services/aiService';

interface AICopilotPanelProps {
  onLoadWorkflow: (nodes: AINode[], edges: AIEdge[], name: string) => void;
  activeAddress: string | null;
}

type BackendBuildResponse = {
  action: 'build' | 'execute' | 'none';
  reason?: string;
  workflow?: {
    name?: string;
    explanation?: string;
    nodes?: unknown[];
    edges?: unknown[];
  };
};

const CATEGORIES = ['trigger', 'action', 'logic', 'defi', 'notification'] as const;
type Category = (typeof CATEGORIES)[number];

const inferCategory = (type: string): Category => {
  if (['telegram_command', 'timer_loop', 'wallet_event', 'webhook_trigger'].includes(type)) return 'trigger';
  if (['send_payment', 'asa_transfer', 'app_call', 'http_request'].includes(type)) return 'action';
  if (['delay', 'filter', 'debug_log'].includes(type)) return 'logic';
  if (['get_quote', 'price_feed'].includes(type)) return 'defi';
  return 'notification';
};

const normalizeNode = (node: any, index: number): AINode => {
  const type = String(node?.type ?? 'debug_log');
  const rawData = node?.data && typeof node.data === 'object' ? node.data : {};
  const rawCategory = String(node?.category ?? '').toLowerCase();
  const category = (CATEGORIES.includes(rawCategory as Category)
    ? rawCategory
    : inferCategory(type)) as Category;

  return {
    id: String(node?.id ?? `node_${index + 1}`),
    type,
    label: String(node?.label ?? rawData?.label ?? type.replace(/_/g, ' ')),
    category,
    // React Flow nodes often keep metadata in `data`; normalize it back into config.
    config: (node?.config ?? rawData?.config ?? node?.params ?? {}) as Record<string, unknown>,
    position: {
      x: Number(node?.position?.x ?? node?.x ?? index * 280),
      y: Number(node?.position?.y ?? node?.y ?? 120),
    },
  };
};

const normalizeEdge = (edge: any, index: number): AIEdge => ({
  id: String(edge?.id ?? `edge_${index + 1}`),
  source: String(edge?.source ?? edge?.from ?? ''),
  target: String(edge?.target ?? edge?.to ?? ''),
});

const AICopilotPanel: React.FC<AICopilotPanelProps> = ({
  onLoadWorkflow,
  activeAddress,
}) => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AIWorkflowResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    if (!prompt.trim()) return;
    if (!activeAddress) {
      setError('Please connect your wallet first.');
      return;
    }

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await api.processAIIntent(activeAddress, prompt) as BackendBuildResponse;

      if (response?.action !== 'build' || !response.workflow) {
        throw new Error(response?.reason || 'AI did not return a draft workflow.');
      }

      const rawNodes = Array.isArray(response.workflow.nodes) ? response.workflow.nodes : [];
      const rawEdges = Array.isArray(response.workflow.edges) ? response.workflow.edges : [];

      const workflow: AIWorkflowResult = {
        name: String(response.workflow.name ?? 'AI Draft Workflow'),
        explanation: String(response.workflow.explanation ?? response.reason ?? 'Draft generated by backend AI.'),
        nodes: rawNodes.map(normalizeNode),
        edges: rawEdges.map(normalizeEdge).filter((edge) => edge.source && edge.target),
      };

      setResult(workflow);
      onLoadWorkflow(workflow.nodes, workflow.edges, workflow.name);
      alert('Draft generated! Review on canvas and click Save when ready.');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setLoading(false);
    }
  }, [prompt, activeAddress, onLoadWorkflow]);

  const presetPrompts = [
    'Send 1 ALGO to address X',
    'Distribute funds to 3 team members equally',
    'Monitor ALGO price and alert when above $0.30',
    'Transfer ASA tokens after checking opt-in',
  ];

  return (
    <div className="ai-panel animate-fadeIn">
      <div className="ai-panel-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <span className="text-sm font-bold text-uppercase" style={{ letterSpacing: '0.06em' }}>
            FluxBot
          </span>
        </div>
        <div className="ai-panel-badge">
          <span className="status-dot status-dot-success"></span>
          BACKEND AI
        </div>
      </div>

      <div className="ai-panel-body">
        {/* Prompt Area */}
        <label
          className="text-xs text-uppercase"
          style={{ display: 'block', marginBottom: '6px', color: 'var(--color-text-tertiary)', letterSpacing: '0.08em', fontWeight: 600 }}
        >
          Describe your workflow
        </label>
        <textarea
          className="ai-prompt-area"
          placeholder="e.g., Send 1 ALGO to address X when price drops below $0.20..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
              handleGenerate();
            }
          }}
        />

        {/* Preset Prompts */}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginTop: '10px' }}>
          {presetPrompts.map((p, i) => (
            <button
              key={i}
              className="btn btn-ghost btn-sm"
              style={{ fontSize: '0.65rem', padding: '3px 8px' }}
              onClick={() => setPrompt(p)}
            >
              {p}
            </button>
          ))}
        </div>

        {/* Generate Button */}
        <div style={{ display: 'flex', gap: '8px', marginTop: '16px' }}>
          <button
            className="btn btn-accent"
            onClick={handleGenerate}
            disabled={loading || !prompt.trim() || !activeAddress}
            style={{ flex: 1 }}
          >
            {loading ? (
              <>
                <span className="loading-spinner"></span>
                GENERATING...
              </>
            ) : (
              '[EXEC] GENERATE WORKFLOW'
            )}
          </button>
        </div>

        {/* Error */}
        {error && (
          <div style={{
            marginTop: '12px',
            padding: '10px 14px',
            background: 'rgba(239, 68, 68, 0.1)',
            border: '1px solid rgba(239, 68, 68, 0.3)',
            borderRadius: '6px',
            color: 'var(--color-error)',
            fontSize: 'var(--text-xs)',
          }}>
            {error}
          </div>
        )}

        {/* Loading Animation */}
        {loading && (
          <div className="ai-loading">
            <div className="ai-loading-dots">
              <span></span><span></span><span></span>
            </div>
            Thinking...
          </div>
        )}

        {/* Result */}
        {result && !loading && (
          <div style={{ marginTop: '16px' }} className="animate-slideUp">
            {/* Workflow Name */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              marginBottom: '10px',
            }}>
              <span className="text-sm font-bold">{result.name}</span>
              <span className="tag tag-sm tag-action">
                {result.nodes.length} nodes
              </span>
            </div>

            {/* Explanation */}
            <div className="ai-response">
              {result.explanation}
            </div>

            {/* Node Preview */}
            <div style={{
              display: 'flex',
              flexWrap: 'wrap',
              gap: '6px',
              marginTop: '12px',
            }}>
              {result.nodes.map((node) => (
                <div key={node.id} className={`tag tag-sm tag-${node.category}`}>
                  {node.label}
                </div>
              ))}
            </div>

            <div className="text-xs text-muted" style={{ marginTop: '12px' }}>
              Draft is already loaded into the builder canvas.
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AICopilotPanel;
